name: DevOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: devops-project-app
  EC2_HOST: 3.138.172.145

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: |
        docker build -t $ECR_REPOSITORY .

    - name: Push Image to ECR
      run: |
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest
        docker tag $ECR_REPOSITORY:latest $IMAGE_URI
        docker push $IMAGE_URI
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker pull ${{ env.IMAGE_URI }}
          sudo docker stop app || true
          sudo docker rm app || true
          sudo docker run -d --name app -p 5000:5000 ${{ env.IMAGE_URI }}
